/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PreGameRouteImport } from './routes/pre-game'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GameOverRouteImport } from './routes/game-over'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PreGameRoute = PreGameRouteImport.update({
  id: '/pre-game',
  path: '/pre-game',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameOverRoute = GameOverRouteImport.update({
  id: '/game-over',
  path: '/game-over',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/game-over': typeof GameOverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pre-game': typeof PreGameRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/game-over': typeof GameOverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pre-game': typeof PreGameRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/game-over': typeof GameOverRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pre-game': typeof PreGameRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/game-over'
    | '/leaderboard'
    | '/pre-game'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/game-over' | '/leaderboard' | '/pre-game' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/game-over'
    | '/leaderboard'
    | '/pre-game'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  GameOverRoute: typeof GameOverRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PreGameRoute: typeof PreGameRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-game': {
      id: '/pre-game'
      path: '/pre-game'
      fullPath: '/pre-game'
      preLoaderRoute: typeof PreGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-over': {
      id: '/game-over'
      path: '/game-over'
      fullPath: '/game-over'
      preLoaderRoute: typeof GameOverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  GameOverRoute: GameOverRoute,
  LeaderboardRoute: LeaderboardRoute,
  PreGameRoute: PreGameRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
